### ISSUE TITLE
Iterator methods are missing from ZstdCompressionWriter

### ISSUE THREAD

**Issue by bra-fsn** [indygreg/python-zstandard#167]
zstandard doesn't have the iterator methods in its `ZstdCompressionWriter`, which might be quite logical, but some libraries, for eg. pandas test the object to be file-like by checking these methods' existence like here:
https://github.com/pandas-dev/pandas/blob/ad190575aa75962d2d0eade2de81a5fe5a2e285b/pandas/core/dtypes/inference.py#L127

Due to this, the following code will die:

```python
import pandas as pd
import zstandard

df = pd.DataFrame({"test": [1]})
cctx = zstandard.ZstdCompressor()
f = cctx.stream_writer(open("/tmp/test.zstd", "wb"))
df.to_pickle(f)
```

with:
```Python traceback
Traceback (most recent call last):
  File "/tmp/test.py", line 7, in <module>
    df.to_pickle(f)
  File "/datasci/lib/python3.8/site-packages/pandas/core/generic.py", line 2957, in to_pickle
    to_pickle(
  File "/datasci/lib/python3.8/site-packages/pandas/io/pickle.py", line 94, in to_pickle
    with get_handle(
  File "/datasci/lib/python3.8/site-packages/pandas/io/common.py", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/datasci/lib/python3.8/site-packages/pandas/io/common.py", line 396, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'zstd.ZstdCompressionWriter'>
```

**Comment by bra-fsn** [comment]
Thanks @indygreg!
