### ISSUE TITLE
read() must be called from an active context manager

### ISSUE THREAD

**Issue by zeromake** [indygreg/python-zstandard#34]
### ENV
1. system: linux
2. python: 3.6.3
3. zstandard: 0.9.0.dev0

### simulation to io.RawIOBase
test.py
``` python
import io
import zstandard as zstd
class ZstdDecompressReader(io.RawIOBase):
    def __init__(self, fp):
        self._fp = fp
        self._eof = False
        self._pos = 0
        self._size = -1
        self._decompressor = zstd.ZstdDecompressor()
        self._stream_reader = None
    def close(self):
        self._decompressor = None
        if self._stream_reader:
            self._stream_reader.close()
            self._stream_reader = None
        return super().close()

    def read(self, size=-1):
        if size < 0:
            return self.readall()
        if not size or self._eof:
            return b""
        if not self._stream_reader:
            self._stream_reader = self._decompressor.stream_reader(self._fp)
        data = self._stream_reader.read(size)
        if not data:
            self._eof = True
            self._size = self._pos
            return b""
        self._pos += len(data)
        return data

if __name__ == '__main__':
    with open('1.tar.zstd', 'rb') as fp:
        decompress = ZstdDecompressReader(fp)
        print(decompress.read(10))
```
python test.py
``` bash
Traceback (most recent call last):
  File "./test.py", line 36, in <module>
    print(decompress.read(10))
  File "./test.py", line 25, in read
    data = self._stream_reader.read(size)
zstd.ZstdError: read() must be called from an active context manager
```
## can run
``` python
import io
import zstandard as zstd
class ZstdDecompressReader(io.RawIOBase):
    def __init__(self, fp):
        self._fp = fp
        self._eof = False
        self._pos = 0
        self._size = -1
        self._decompressor = zstd.ZstdDecompressor()
        self._stream_reader = None
    def close(self):
        self._decompressor = None
        if self._stream_reader:
            self._stream_reader.__exit__()
            # self._stream_reader.close()
            self._stream_reader = None
        return super().close()

    def read(self, size=-1):
        if size < 0:
            return self.readall()
        if not size or self._eof:
            return b""
        if not self._stream_reader:
            self._stream_reader = self._decompressor.stream_reader(self._fp)
            self._stream_reader.__enter__()
        data = self._stream_reader.read(size)
        if not data:
            self._eof = True
            self._size = self._pos
            return b""
        self._pos += len(data)
        return data

if __name__ == '__main__':
    with open('1.tar.zstd', 'rb') as fp:
        decompressor = zstd.ZstdDecompressor()
        decompress = ZstdDecompressReader(fp)
        print(decompress.read(10))
```

``` python
import io
import zstandard as zstd
class ZstdDecompressReader(io.RawIOBase):
    def __init__(self, decompressor, stream_reader):
        self._fp = fp
        self._eof = False
        self._pos = 0
        self._size = -1
        self._decompressor = decompressor
        self._stream_reader = stream_reader
    def close(self):
        self._decompressor = None
        if self._stream_reader:
            self._stream_reader.close()
            self._stream_reader = None
        return super().close()

    def read(self, size=-1):
        if size < 0:
            return self.readall()
        if not size or self._eof:
            return b""
        if not self._stream_reader:
            self._stream_reader = self._decompressor.stream_reader(self._fp)
        data = self._stream_reader.read(size)
        if not data:
            self._eof = True
            self._size = self._pos
            return b""
        self._pos += len(data)
        return data

if __name__ == '__main__':
    with open('1.tar.zstd', 'rb') as fp:
        decompressor = zstd.ZstdDecompressor()
        with decompressor.stream_reader(fp) as stream_reader:
            decompress = ZstdDecompressReader(decompressor, stream_reader)
            print(decompress.read(10))
            print(decompress.read(10))
```
### suggest
So should it be not context manager

**Comment by indygreg** [comment]
Thinking about this some more, I agree that the `stream_reader()` and `stream_writer()` interfaces should not require a context manager. I'll try to work this into the next release.
